# Generated by Django 4.1.1 on 2022-11-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzes',
            name='points',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
