# Generated by Django 4.1.1 on 2022-11-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizzes_points'),
        ('module', '0004_module_assignments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='quizzes',
            field=models.ManyToManyField(related_name='quiz', to='quiz.quizzes'),
        ),
    ]
